---

- name: Execute timescaledb-tune
  command: /usr/bin/timescaledb-tune -yes -max-conns {{ timescaledb_tune_max_conns }}
  notify: restart postgresql
  register: results

- name: Results
  debug: var=results
  when: timescaledb_tune_results == True
