---

- name: Execute timescaledb-tune
  command: /usr/bin/timescaledb-tune -yes
  notify: restart postgresql
  register: results
  when: timescaledb-tune == True

- name: Results
  debug: var=results
